# Measures

Copies of all measures can be found in the [proj_optimize repo](https://github.com/jjcurtin/proj_optimize/tree/main/methods/measures)


## Baseline Survey
[Qualtrics Survey](https://uwmadison.co1.qualtrics.com/jfe/form/SV_6gkdO0ZmIYoTXT0?practice=true)

### ID:

* Demographics 
* Alcohol Use History 
* WHO-Assist 
* Trust ID 
* Tone preferences 
* Alcohol Abstinence Self-Efficacy Scale AASE (added 2026_0327)

### Repeated

* Drinking Motives Questionnaire for Adults (DMQ-A)
* Flourishing Measure 
* GAD-7 
* PHQ-9
* Multidimensional Inventory of Recovery Capital (MIRC) 

Questions for lab:

* keep 2 optional questions on flourishing?
* inclusion and placement of STAR questions on trust_id?



## Mid and Endpoint Repeated Measures Survey

* 8 & 16 weeks
* Also TLFB by interview

### Repeated

* Drinking Motives Questionnaire for Adults (DMQ-A)
* TOAST Trust 
* Message Usefulness
* Digital Working Alliance Inventory (D-WAI)
* Flourishing Measure
* GAD-7
* PHQ-9
* Multidimensional Inventory of Recovery Capital (MIRC) 


### Daily
* EMA 
  * Will come at the end of the day, at 4pm local tz. People can choose their reminder time.
  * They will have until noon of the following day to complete it.
  * We will include location script calculations from day 1, because at intake we will get places they are trying to avoid. This can be asked immediately.
  * After that we will ask only TWO locations per day max (decided by JC 2026_0501)
* Feedback
  * Will come at the start of the day, at 6am local tz.  People can choose their reminder time.