# Methodology

This section contains methodological information for the study.

## PRELAUNCH STATUS

### TO DO:
* Update recruitment documents
* IRB submission
* Update CT.Gov office
* Update website
* Set up OnCore & new Participant Payments
* Data Management site initiation visit
* Recruitment plan
* SOP for fully putting someone on study using STAR
* final review of all implementations below

## Decisions
* Raw data storage will be at both the subid level and aggregate
  * both located on R drive
* Processed data on S drive

## Data Pipeline Overview

### Data collection tools:

1. Qualtrics forms
2. NDA GUID tool
3. FollowMee

### PRISM data fetch scripts:

These R scripts are run by prism:

1. daily_download.R: Downloads GPS to `R:/optimize/$subid/gps/` and `gps_$subid.csv` 
   a) Runs hourly on the hour
2. download_qualtrics.R: Download qualtrics surveys:
   a) screen, guid pedigree, baseline, ema, feedback, bimonthly
   b) runs 4x day at 00:05, 06:05, 12:06, 18:05.
   c) **NEEDS UPDATE**: Add consent, onboard, feedback (dependent on finalizing feedback survey form), and staff scripts.
3. find_new_locations_opt.R: Detect new locations for each subid, save to `R:/optimize/$subid/places.csv` 
   a) runs 4x day at 00:30, 06:30, 12:30, 18:30.
4. **NEED SCRIPT.R**: update_places.R. Checks downloaded ema.csv and updates places file for each participant with newly provided context. 
   a) will run hourly? 4x? so that places are continually updated
5. **NEED SCRIPT.R**: Script to create new contact list and update it
   a) Update as participants are added/removed
   b) Update daily with gps locations which need context
6. **NEED SCRIPT.R**: Script feature engineers features from GPS and EMA - what is saved and where:
   a) not for participants who are not on study
   b) features run subject by subject and saved by subid - just append new features
   c) each subid folder will have a feature file 
7. **NEED SCRIPT.R**: Script that runs the prediction model for all active participants - also by individual subid
   a) saved as columns in the feature file
   c) current prob and cx in prob also saved
8. **NEED SCRIPT.R**: Script to calculate feature importance for all active participants - 
   a) run by subid for each day,
   b) they get an importance value for each feature. Use this + the previous day most important feature to 
    select new most important feature which is also saved to a subid based file
9. **NEED SCRIPT.R**: Script to create the daily support message for each participant - creates the daily message
   a) will include recovery activity from 5 & 6- do we save that somewhere?
   b) also saves their yoked tone preference. Somewhere there's a file for each participant with
      their singular tone and style

### Staff data manipulation for running the study:

1. create_bulk_guid.qmd: creates identity file from Qualtrics onboarding script for NDA GUID creation tool
2. format_nda_data.qmd: Creates the formatted template files for uploading data to NDA
3. **NEED SCRIPT.R**: update_participants.R AND/OR qmd. (Might need both)
  a) Updates a PRISM participant list on the R drive automatically so we have a running record of participants (PRISM list will only have on-study?) 
  b) Also needs to be run by an RA manually after consent/interview to update when someone is added to or taken off study.
4. **NEED SCRIPT**: check_adherence.qmd (start from Risk2 script)
5. **NEED SCRIPT**: make_payment.qmd (start from Risk2 script) 
6. **NEED SCRIPT**: enrollment_rppr.qmd (creates updated RPPR enrollment csv)


Data analysis:

* TBD

## Qualtrics forms

### Participant facing

* [Screening](https://uwmadison.co1.qualtrics.com/jfe/form/SV_eKvAYBgOhNYxjL0?practice=true)
   - needs final review to ensure implementation matches finalized version
   - needs lab review 
   - use responseID as screen_id which can be carried forward to consent (inserted in URL by RA)
* [Consent](https://uwmadison.co1.qualtrics.com/jfe/form/SV_2gwLTMnX7WdgEPY?practice=true) 
   - needs lab review
   - will need to be updated post-IRB change approval
   - needs forwarding to onboard survey
* [Onboard](https://uwmadison.co1.qualtrics.com/jfe/form/SV_1NecAUeTKptN4ua?practice=true) 
   - needs lab review
   - collects phone number and address for EMA & payment
   - may change per new participant payment regulations
   - needs forwarding to birth data survey
* [Birth data](https://uwmadison.co1.qualtrics.com/jfe/form/SV_9uCe7FPCGeHqriu?practice=true) 
   - needs lab review
   - subid assigned here, unless decided otherwise
* [Baseline measures](https://uwmadison.co1.qualtrics.com/jfe/form/SV_6gkdO0ZmIYoTXT0?practice=true)
   - SW final review to match 2026_0309
      * keep 2 optional questions on flourishing?
      * inclusion and placement of STAR questions on trust_id?
   - needs lab review
   - DONE add subid as embedded data
* [Mid/end repeated measures](https://uwmadison.co1.qualtrics.com/jfe/form/SV_3w3BqdZl0fPfMa2?practice=true)
   - needs final review to ensure implementation matches finalized measures
   - needs lab review
   - add subid as embedded data
   
The following are not finalized in qualtrics as significant revision is happening:

* Daily EMA
    - MEASURE NOT FINALIZED
       - valence/arousal question
       - add #drinks question?
       - implement lapse calendar date/time select 
          * easier if we limit the date range they can add unreported lapses - say, last 7 days?
* Location context (part of EMA after day 7)
    - MEASURE NOT FINALIZED
    - modify for the survey to be rebuilt from data daily by script, rather than have qualtrics pull from PRISM
* Daily Feedback
    - needs update when we get final models
    - modify for the survey to be rebuilt from data daily by script, rather than have qualtrics pull from PRISM



### RA facing:
* RA session form
  - collects daily EMA times
* Date log form
* WOG
* TLFB (gathered by interview)
   - Needs calendar added and finalization of what is to be collected (only n drinks, also hours drinking, etc)
* Exit Interview (gathered by interview)

## FollowMee

Input: 

1. Installed with token on participant phones
2. Administration done from web dashboard

Output: 

1. 3-14 days of data.
2. There will be 24x daily automated data pulls by script, saved as daily and study-longaggregate csv files (subid level vs all aggregate?).

## Scripts

These live in the proj_optimize repo where they will be called by PRISM. More will be added as they are completed

automation: 

* task_scheduler_opt.R - schedules R scripts to run
* daily_download_opt.R - downloads GPS
* mak_daily_qualtrics.R - downloads survey data from qualtrics including EMA
  * part of it will download EMA times from the RA session survey to be used by PRISM
  
scripts_staff:

* create_bulk_guid.qmd - formats a dataframe downloaded from qualtrics to be used in the NDA GUID tool
* format_nda_data.qmd - formats qualtrics data for NDA upload
  * format_nda_templates.R (helper script for above)

scripts_prism:

* find_new_locations_opt.R - pulls user GPS data and finds new locations to query in EMA location context questions

NEED TO ADD:

* John's model script 
* recommendation script
* mak_payments
* chk_adherence


## PRISM

Input:

1. See csv files listed [here](https://jjcurtin.github.io/docs_optimize/prism.html#config) - NB these can be updated from script OR manually

Output:

1. EMA messages linked to a qualtrics survey with location questions
2. See csv files listed [here](https://jjcurtin.github.io/docs_optimize/prism.html#data)


## NDA GUID tool

Input: RA batch loads CSV file pulled from Birth Data qualtrics form (Currently only Susan can do this)
Output: CSV file with GUID added for use in NDA

## OnCore

Input:  

* Participant ID information (batch upload or manual?) 
* Participant eligibility information 
* Participant visit information

Output: Whatever the CT oversight group needs - Not for study data collection, although it will provide visit information


## SOPS

See [SOPs](sops.qmd)

## Recruitment

### Soft Launch
* Craiglist ads in Madison/Milwaukee/Chicago
* Possibly bulk email to UW staff & students?

### Advertising
* Craigslist
* Reddit
* Clinic partnerships, if we can find them



