# Participant Payments

Payment is via a reloadable debit card or direct deposit. 


## Overview

### Paying participants

Each month, Susan will calculate adherence and payments, and post payments to be made in the participant's thread.

1. In the top menu, under Payments, select Participant Check in. 
2. You can search by name under Participant Search, or use Protocol Search and type "Curtin" to show our protocol, and all active participants.  We do not have subid in the system so you will need to check the onboard.csv to match the name to the subid.
3. Find the visit or visit Susan named in the participant thread.
4. If the visit has a stipend listed, simply indicate that the visit has Occurred, and then hit Send for Review.
5. If the visit has 0.00 as the stipend amount at the top, it means there will be an Ad Hoc Stipend. Scroll down to where you see "Have ad hoc stipends?" and change the slider to Yes.
   * Enter the amount specified and in the comment, explain what it's for (for example, the number of EMA they completed). This can be copied from the participant thread as well.
6. Hit Send for Review.
7. Tag Susan in the participant thread to go in and Review/Approve the payments.
8. Send a payment message to them by email using the template on the [Staff Scripts](staff_scripts.qmd) page

### Review payments

* Any payments submitted for review will appear in the Payment console. * Here the UW financials team can review the payments and choose to Pay or Reject a stipend or reimbursement. 
* Clicking on the payment anywhere in the table allows you to access the visit details. Here you can review reimbursement guidelines, amounts entered by study staff, and any comments and attachments. 
* Once the reimbursement is reviewed, clicking Pay will release funds to the participant or clicking Reject will reject the payment.
* In addition to payment amounts and comments, reviewers can also access an audit trail with a full history of changes to the stipend or reimbursements. 

### Reporting

* 1099 report returns participant information (such as name, address, and SSN) as well as the total amount of payments they've received within the search window. It is designed to provide us with information to easily generate 1099 forms. 
* The card inventory report lists the ICNs of cards at UW. The report will list the card status, when it was created, and the expiration date of the card. 
* The itemized receipts report lists all of the stipends and reimbursements that have been remitted to participants, as well as associated fees. There is a tab for every protocol as well as a summary tab that lists the totals for each protocol. 
* The sponsor invoicing report organizes all payments to participants by protocol. It lists payments as well as card fees to help efficiently invoice study sponsors. (NB We will not be using this as we do not receive sponsor payments)

### Manage Protocols and Participants

* All of your protocol records will be listed on the Protocols landing page. 
* Further down the protocol record, you will find the visits and stipends information. This is also where financial specialists will be able to set up any applicable reimbursements.
* There are fields where you can define reimbursement maximums and mileage rates. These amounts flow to other areas of Payments so that study and financial teams have easy access to that information. You also can also add protocol users to grant them access to the protocol. 

### Participants

You can use Participant Search to find and manage participant records in Payments.

* After clicking Edit, you are able to view the participant's contact information. 
* you can click the All Visits/More Details link to see a full schedule of visits for that protocol. This also displays a history of any checked in and paid visits.

### Roles
What each role does in Participant Payments:

* Participant Confirmation: Enrolls participants, marks visits as occurred
* Participant Confirmation +Pay: Enrolls participants, marks visits as occurred, and requests payments
* Financial/Protocol Coordinator: Creates visits/stipends in Payments' protocol and adds staff
* Principal Investigator or Program Manager: Has ability to review assigned protocols and run reports (no PHI)
* Reviewer: Reviews initial stipends for approval and enters participants into ShopUW+ if >$250
* Custodian: Has business unit oversight and manages cards
* Dean's Office: Approves protocols to be in Payments; reviews and authorizes travel reimbursements

## Adding/managing participant records
* Before adding a participant in Participant Payments, you should search for the participant to make sure they have not already been added to the system.
   * Go to Menu > Payments > Participant Check-in
   * start typing in the Search field.
   * Alternatively, you can use the Participant list to search for a participant:  Menu > Admin > Participants 
   
   * If the participant has not yet been added, you will see a message that says No records found.
   * If your protocol is in OnCore, you will need to register them to your protocol in OnCore, not in Payments. Registration in OnCore will create their record in Participant Payments.
* If you locate the participant's record, you can tell at a glance whether the participant has been imported from OnCore or created manually - A participant's record that is imported from OnCore will display a cloud symbol followed by a message stating that the participant was imported from the Advarra Hub

### Updating participants

To Edit, you must open the record through the Participant Check-In. 

*  buttons to indicate whether the participant will be paid by direct deposit to their checking account or by giving them a physical payment card. 
* If the participant opts for direct deposit to their checking account, they will receive an email with instructions to set up an account. They will enter all of their checking account information there. You will not handle their account information.
   * IMPORTANT! We still have to collect the W9
* Add Card ICN if Issuing a Payment Card. The ICN is the 7-5 digit number below "Valued Cardholder" on the front of the card. It displays through the front of the sealed envelope holding the card. Do not open the envelope! 
* Record the ICN of the card in the participant's record in Payments at the time you give them the card. 
* Do not enter a card ICN into a participant's record until they have chosen card vs ACH (direct deposit/check).
* Entering a card early creates an unnecessary risk of giving the card to the incorrect participant!

### Error messages
* A yellow piggy bank icon may appear. This indicates there is something that needs attention.(Payment is not yet processed, acccount info incomplete, missing SSN)
* A red piggy bank icon would mean there is invalid information in the record that needs to be fixed.
* An uncolored piggy bank icon means the account is ready to use.
   * Hover over for the status (in our case, it says whether they will get funds in a checking account or on the prepaid card)

## Adding a participant to a protocol
After a participant is in the system, you can add them to a protocol.

* Search for the participant, and select them. You should see an area that says "Add Participant to:" with a box to Search for Protocol.
* You can search by protocol number, NCT number, or title.
* Click to select and add the participant to the protocol.

## Issuing Payments
Requesting payment for a participant involves three quick steps:

1. Select the Visit
2. Confirm the visit stipend
3. Request reimbursement (if applicable)

* When you have opened the participant's record and located the protocol, the Next Visit to be documented will be listed. In Payments, you will click on "Next Visit: Visit X" to open that visit.
* In the Visit Stipend section, the Occurred button is selected by default. The approved stipend amount is listed and cannot be edited. 
* You will simply click Pay to submit the payment request.
   * You may see an alternative button that says Submit For Review in place of Pay. Either button will submit the payment request.
   * If a scheduled visit did not occur, you can mark it as Missed or N/A as appropriate. If Missed or N/A is marked, the participant will not be paid and you cannot request reimbursements for that visit.
* If there will be reimbursements requested, select Yes next to Have Reimbursements? After selecting Yes, fields become available for you to enter information for the reimbursements. The comments field allows you to enter any info that you need to communicate to the financial team to review.
* After entering all the pertinent reimbursement information, click Send for Review to complete the process.
* You will see check marks next to both Visit Stipend and Visit Reimbursements after you have answered both sections.
* Staff with a Financial Reviewer role in Participant Payments must review the initial visit for each participant after you have submitted that stipend request as shown above. When they confirm the visit occurred, they click a "Pay" button, which distributes the stipend to the participant's account.

For subsequent visits:

* If you have a Participant Confirmation +Pay role, you will see a Pay button and the funds will be distributed to the participant's card or ACH method of choice right away.
*If you have a Participant Confirmation role (that does not include +Pay), you will still see a Submit For Review button, and a Reviewer must go into the system and click the Pay button.

### Viewing Visits
* You can view past visits in the participant's record by opening the All Visits / More Details hyperlink.
* This is also where you go to ad Unscheduled visits. To open the Unscheduled Visit, in Participant Payments you click on the text that says Create Visit: Unscheduled Visit 1.

### What if a request was rejected?

If a stipend or reimbursement request you submitted was rejected:

* The Reviewer is responsible for emailing the study team to let you know it was rejected
* If you need to resubmit the request by amending the request, you will need to communicate the changes to the Reviewer through email.
* If the changes are sufficient for the Reviewer to approve the request, the Reviewer will undo the rejection, make the change manually in Payments, and then approve the payment.

 

If you are not a Reviewer, you can still see the progress in the Payments system if you look at the Visit Details.

* It will tell you the payment status for individual requests.
* Communicate with the Reviewer to resolve any issues.

## Reviewing Payments

In Advarra Participant Payments, if reimbursements have been submitted for review, or if a stipend payment has been requested by someone without the ability to approve payments, financial staff will see these appear in the payment review.

Only Dean's Office staff should review and approve/reject Reimbursement requests. Reviewers outside of the Dean's Office can review stipend requests.

* To open the Payments Review  list, click Menu > Payments > Payment Review.
   * From the Payments Review list, you can quickly see payment details, such as the protocol number, visit details, payment type, and more.  You can also pay or reject payments.
* If you would like to look at the details or edit the amounts before approving a payment, you can click the line of the payment you want to examine.
* Use the pay and reject butons as quick actions

When approving a payment:

1. No matter what exploring or reviewing you do on a pending payment, clicking Pay is the only way you can approve that payment.
2. Make sure you are on the correct line for the payment you are attempting to pay or reject. You may want to use filters to reduce the list size in order to minimize the risk of clicking on the wrong Pay or Reject button.
3. When you click Pay or Reject on a line item, that item will disappear from your list (assuming the default Pending option is displayed in the Status field).

### Rejecting payments

There may be situations when you need to refuse or reject a reimbursement or stipend for a participant. 

For example, you may need to reject a payment if the amount is more than allowed, or if the participant was added to the wrong protocol.

**Notify the Study Team if you Reject a Payment**

Participant Payments does NOT send a notification when a payment is rejected.

As a result, if you are reviewing a payment request and reject it, you will need to email the study team to let them know it has been rejected.

You may also enter a comment in Participant Payments in addition to the email communication.

You are able to undo a rejection in Participant Payments if you clicked Reject by mistake or if the study team has made corrections to the request that make the request acceptable for payment.

1. Update the Payment Status field to Rejected.
2. Locate the rejected payment you wish to undo.
3. Click the Undo Reject button in the far right column of that payment's row.


## Replacing payment cards

### Lost or Stolen cards

* During normal business hours, participants should contact their study coordinator directly. This will ensure a new card is issued and no one else can use the funds on the card.
* After normal business hours, participants should call Account Holder Services at 1-855-316-5166 to disable the card immediately. 
   * Participants will need to contact you as soon as possible (the following business day) to have a new card issued.

If the participant contacts you to report a lost or stolen card, you should immediately update the participant's record in Payments. You will need the following information:

* Participant's name
* ICN of new card that will need to be assigned to participant 

You can instantly cancel a participant's card and transfer all funds to a new ICN within Participant Payments.

1. navigate to Menu > Admin > Replace Payment Card.
2. A search field will appear, where you type the name of the participant whose card needs to be replaced.
3. After you select a participant, you will see the Replace Payment Card screen. It will display the participant's name, email address, date of birth, and any identifiers previously entered into Participant Payments. You will also see the old ICN number and a field to enter the new ICN. 
4. To process the replacement, type the new ICN into the field, then click Replace. This will transfer all funds to the new card. Those funds will be available immediately.


### If you get an error:

If you encounter an error, contact Advarra Payments Support and they will replace the card for you.   

* Phone: 608-826-7800
* Email: paymentssupport@forteresearch.zendesk.com(opens in a new tab) 

To protect PHI when emailing, do not send the participant's name, email address, or any screenshots of PHI. 

Instead, send the URL for the participant page in Advarra Participant Payments.

To locate the URL for the participant page:

1. In the Participant list, search for and click on the participant's name
2. Copy the URL from the participant's record within Participant Payments.
3. Paste the URL into an email and send it to the Advarra Support team to research for you.

Example email:

> Hello,
> 
> I am trying to replace a payment card for one of our participants and have run into an issue. Can you please look into this for me? The participant's URL is: [insert URL here].
> 
> Please call me if you have any questions at [insert phone number].
> 
> Thank you!
> 
> My Name
> UW-Madison


Note: he participant's account and password on Hyperwallet, the website where they access their payment information, will remain the same even if they need a replacement card.

### Expired cards

As with most credit or debit cards, they have a shelf life or expiration date.  Expiration dates are placed on cards primarily for normal wear and tear.  The card can become worn out or the plastic can break. 

Participant Payment cards are no different.

Payment cards expire every three years from the date the card was issued to UW. 

This means the start date of that three years is when the SMPH Dean's Office received it, not the date they issued it to your study team nor the date you issued the card to the participant.

The funds do not expire, but the cards themselves do.  If the card has expired, it will automatically be disabled for the participant

Participants must contact their study coordinator to request a replacement if their card has expired.  

Follow the same process you would for replacing a lost or stolen card to replace an expired card.

## Payment info for participants

Any documents you plan to share with participants must be approved by the Institutional Review Board (IRB) of record for your study before you give those documents to the participants.


Once you have IRB approval for payment-related documents, you will share them with your participants as appropriate. 

There are separate documents available to give participants who choose a Payments Card versus participants who choose direct deposit (ACH), since their account setup process will be different.

You will give each participant the corresponding cardholder or direct deposit informational sheet.

You can find the most up-to-date resources, including document templates for you to submit for IRB approval, on the SMPH Informatics KnowledgeBase (KB) at https://kb.wisc.edu/smph/informatics/

You are required to document confirmation that the participant received the appropriate cardholder or direct deposit information.


Each payment-related document has a place to capture participant information that is necessary for their account setup in Payments, as well as their signature and date.


Save a copy of the signed document(s) for each participant. 

To do this, you can:

* make a physical copy of the signed document, OR
* scan the document and save it electronically, OR
* take a picture of the document using a university-owned device (do not use a personal device to do this!) and upload the picture to your study file, OR
* present two copies of the page to the participant, have them sign both, then you keep one for your files and they keep the other

There is no location in the Participant Payments system to upload these documents. Your study team will need to identify a location to store these documents. 

Your study team may opt to upload them into OnCore. In OnCore, the appropriate location would be in the Subject Console > Documents tab for each participant record.

* You (the study coordinator) are responsible for making arrangements to get the new card to the participant.
* You can mail it to the participant after confirming their address, or have them pick it up, for examples.

 

What if I don't have any extra cards?

* Contact your department's Custodian to acquire additional cards.


## Navigation

To add an item to the favorites bar, select the item through the Menu, then click the start next to that item. You can add either a category or a specific sub item in that category. 

You can move items by clicking and holding, then move it where you want it.

You can remove the item by clicking the highlighted star again.

## User Profile

You have access to edit your title and contact numbers within your User Profile. 

## Contacts page

These are not participants, but other users in the system.






## Managing protocols in payments
Before creating a protocol in Participant Payments, you will need to submit an intake form to get approval. More information about this process is covered in the Canvas course or [here](https://kb.wisc.edu/smph/informatics/)

The protocols landing page will display all the available protocols.

Info includes:

* Protocol Number
* NCT Number
* Protocol Name
* Participant Payments Status

### Protocol creation from Oncore
In OnCore, an Administrator will update the protocol to create the record in Payments automatically unless the protocol status is Abandoned, Terminated, or IRB Study Closure.

* DO NOT change the field "Enable Payments Integration" in OnCore.
* Oncore protocols will display a cloud symbol followed by a message stating that the protocol was imported from the Advarra Hub
* Imported protocols start as Inactive. After you have set up visits you can switch to Active.

### Editing the Protocol 

Can Edit:
1. IRB Number
2. Financial Reference Number (full funding string)
3. Internal Reference Number (this is "project number")
4. Keywords, to help with protocol searches (like short title)
5. Business Unit (dropdown, select dept/division)
6. Whether Reimbursements are Allowed for this Protocol
   * Allowable: Parking, hotel stay, mileage, **other** (can we use this for EMA?)
7. Whether the Protocol is Active - click Yes when ready to start paying. All visits & reimbursements with stipend amounts must be set up first.
8. Visit Information - you can add visits here, both scheduled and unscheduled


### Adding Visit Details

* In the Protocol Details, you will create an entry for every expected visit. You will need to add a description and stipend amount for each visit.
* If reimbursement is allowed, you will also add reimbursement types.
* After clicking Add Visit, you fill out name and stipend, and click again to add another field.
  * Use the order arrows to put them in the correct order. (Or click and drag)
* Unscheduled visits are those that may not be done for all participants, but they MUST be added
* A reimbursements field will appear once those are enabled and selected for each visit. Leave blank if not using it (aka hotel reimbursement)

### Adding protocol users
After entering the protocol details, you can add staff to the Protocol Users list. 

* click the add button above the list of protocol users. Search & add.
* Once the user has been added, they will then be able to pay stipends and reimbursements for this protocol, if their Payments permissions allow.



## Reports in payments

The ability to run reports in Participant Payments requires specific permission. If you should have this permission but are unable to run reports, contact the Support Team to request it be added to your account.

The reports available come standard with Participant Payments. At this time, we do not have the ability to create custom reports.

* In Menu > Reports, you will see a list of the standard reports available. 
* To select a report, click on the hyperlinked name of that report.
* After selecting a report, if there are report parameters, you will be taken to the appropriate screen to set those parameters.
   * You can also select in which format you want the report to be delivered.
* Clicking Run will generate the report.
* Download it by clicking View Output in the Queued Tasks 

### Available reports

* The 1099 Report provides information for all participants that have received payment within the search period. It shows a sum of all stipends paid to participants, contact information, and SSN. The amounts reflected in this report do not include reimbursements.
   * There is also an Invalid SSN identifier that flags participants who have been paid more than $249 and do not have a valid SSN on file. 
* All transactions report lists all paid transactions within a specified date range. This report contains protocol and visit information, and amounts paid. It also contains patient identifiers, if used, but does not contain additional identifying information such as patient names and addresses. 
* Card inventory report shows all cards at UW-Madison, as well as their assigned status and expiration dates. 
* Incomplete participant registrations report lists participants enrolled on a protocol that need to have their payment account registration completed. 
* Itemized receipt report lists all participant payment and fees within a specified date range. The spreadsheet has a separate tab for each protocol and a summary of the protocols on the Total tab.
* Payment Audit report shows any changes made to payments within a specified time period. For example, if a reimbursement is approved, rejected, or modified, these changes will be listed.
* Payments Contact Audit report lists a report of all users in our instance of Participant Payments and their associated User Roles as well as other user information such as last login date and time. 
   * There is also a Payment Contact Audit Report by Protocol option.
* Sponsor invoicing report lists payments and associated fees, organized by protocol. There are columns to show the payment type, amount, any associated fees, and the total. 



## Using participant pauyments at UW Madison

[SMPH Research Informatics KB](https://kb.wisc.edu/smph/informatics/internal/search.php?cat=13860) has reference info.

* FAQs
* Workflows
* Data Field Definitions
* Card Management Information
* How-To Instructions for Payments Tasks
* Links to Required Forms and Participant Resources

If you cant find the info ask the [Application Support Team](https://smph-navigator.atlassian.net/servicedesk/customer/portal/69/group/217)


* If you have questions about a specific protocol record, include the protocol number in the description.
* If you have questions about a specific participant's record, include the URL from their record (you can retrieve this through the Participants list or Participant Check-In after searching for the participant in question).
   * This allows you to communicate the record without including PHI in the description.
* Do not include PHI when using the JIRA portal to contact the Support Team.

When you have completed all the required modules for your role(s), submit your course completion using the link provided in the email preiously sent to you with a subject of "Participant Payments Training for UW-Madison".


